import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="The Turning", page_icon="◌", layout="wide", initial_sidebar_state="collapsed")

st.markdown("""
<style>
.stApp { background: #090b0f; }
[data-testid="stHeader"] { background: rgba(0,0,0,0); }
.block-container { padding: 0.75rem 1rem 1rem; max-width: 1800px; }
iframe { border-radius: 18px; }
</style>
""", unsafe_allow_html=True)

HTML = r'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>The Turning</title>
<style>
:root{--bg:#080a0d;--panel:rgba(12,15,20,.82);--line:rgba(255,255,255,.10);--text:#ebe8df;--muted:#aaa79f}
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}
#app{height:100vh;position:relative;background:radial-gradient(circle at 50% 30%,#162022 0,#090b0e 50%,#060709 100%)}
#world{position:absolute;inset:0}.brand{position:absolute;top:22px;left:24px;z-index:10;pointer-events:none}.brand h1{font-family:Georgia,serif;font-weight:500;letter-spacing:.08em;text-transform:uppercase;margin:0;font-size:28px}.brand .sub{font-size:11px;letter-spacing:.23em;text-transform:uppercase;color:var(--muted);margin-top:5px}
.hud{position:absolute;right:18px;top:18px;width:315px;max-height:calc(100vh - 36px);overflow:auto;z-index:12;background:var(--panel);backdrop-filter:blur(16px);border:1px solid var(--line);border-radius:18px;padding:15px}.section{padding:0 1px 14px;border-bottom:1px solid var(--line);margin-bottom:14px}.section:last-child{border:0;margin:0}.eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.2em;color:#9c9a93;margin-bottom:7px}.labelrow{display:flex;justify-content:space-between;align-items:center;margin:8px 0 4px}.labelrow span:first-child{font-size:12px}.val{font:11px ui-monospace,monospace;color:#bbb}input[type=range]{width:100%;accent-color:#9fc3ad}.pills{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.pill{padding:7px 8px;border:1px solid var(--line);border-radius:10px;background:rgba(255,255,255,.025)}.pill b{display:block;font-size:10px;text-transform:uppercase;color:#9e9f9a}.pill span{font:12px ui-monospace,monospace}.actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.btn{border:1px solid var(--line);background:rgba(255,255,255,.055);color:var(--text);border-radius:10px;padding:9px 10px;font-size:11px;text-transform:uppercase;cursor:pointer}.btn.primary{background:rgba(140,190,160,.12)}
.chronicle{position:absolute;left:22px;bottom:20px;width:min(620px,calc(100vw - 390px));z-index:11;background:linear-gradient(180deg,rgba(10,12,15,.50),rgba(8,10,13,.86));backdrop-filter:blur(12px);border:1px solid var(--line);border-radius:18px;padding:16px 18px}.chapter{font:500 19px Georgia,serif;margin-bottom:8px}.story{font:15px/1.55 Georgia,serif;color:#ddd9d0;min-height:72px}.meta{display:flex;gap:12px;margin-top:10px;font:10px ui-monospace,monospace;color:#98958e;text-transform:uppercase}.moralbar{height:5px;background:#202329;border-radius:999px;overflow:hidden;margin:4px 0 8px}.moralbar i{display:block;height:100%;background:linear-gradient(90deg,#b28c69,#b9d7c1)}.soul{font:12px/1.45 Georgia,serif;color:#bcb8ae;font-style:italic;margin-top:6px}#omen{position:absolute;left:50%;top:20%;transform:translate(-50%,-50%);z-index:9;font:500 15px Georgia,serif;letter-spacing:.12em;text-transform:uppercase;color:#f2e5c9;opacity:0;transition:opacity .6s;pointer-events:none}
</style>
</head>
<body>
<div id="app">
<div id="world"></div>
<div class="brand"><h1>The Turning</h1><div class="sub">A life shaped by pressure, memory & chance</div></div>
<div id="omen"></div>
<div class="chronicle"><div class="eyebrow" id="dateLine">Year 1 · Early Spring</div><div class="chapter" id="chapter">Awakening beside the dead machine</div><div class="story" id="story">A traveler wakes in wet grass beneath a pale sky. Behind them, a machine large enough to have once carried a village sits silent and half-buried. They remember their name—Mara—but almost nothing else.</div><div class="meta"><span id="age">Age 24</span><span id="place">The Hollow</span><span id="generation">Life I</span></div></div>
<aside class="hud">
<div class="section"><div class="eyebrow">World Pressures</div><div id="sliders"></div></div>
<div class="section"><div class="eyebrow">Inner Weather</div><div class="pills" id="traits"></div><div class="soul" id="soulLine"></div></div>
<div class="section"><div class="eyebrow">Moral Tensions</div><div id="morals"></div></div>
<div class="section"><div class="eyebrow">Time & Retelling</div><div class="actions"><button class="btn primary" id="pauseBtn">Pause</button><button class="btn" id="speedBtn">1× Time</button><button class="btn" id="nudgeBtn">Turn the Wheel</button><button class="btn" id="rebirthBtn">Rebirth</button></div></div>
</aside></div>
<script type="importmap">
{
  "imports": {
    "three": "https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js",
    "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/"
  }
}
</script>
<script type="module">
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)), choice=a=>a[Math.floor(Math.random()*a.length)], lerp=(a,b,t)=>a+(b-a)*t, sig=x=>1/(1+Math.exp(-x));
const pressures={abundance:.55,danger:.36,community:.44,mystery:.68,change:.48,freedom:.62,technology:.24,fate:.50};
const labels={abundance:'Abundance',danger:'Danger',community:'Community',mystery:'Mystery',change:'Change',freedom:'Freedom',technology:'Technology',fate:'Fate'};
let soulEchoes=[], state, speedIndex=0; const speeds=[1,2,4], seasons=['Early Spring','High Summer','Late Autumn','Deep Winter'];
function logStory(text){document.getElementById('story').textContent=text;}
function flashOmen(t){const o=document.getElementById('omen');o.textContent=t;o.style.opacity=1;setTimeout(()=>o.style.opacity=0,1500)}
function rebirthText(){if(!soulEchoes.length)return 'The world folds inward and begins again. Mara wakes beside the dead machine with no memory of another life, though the morning feels strangely familiar.';const e=choice(soulEchoes);return `The world begins again. Mara wakes beside the dead machine. Nothing of the former life can be recalled, yet ${e.phrase}.`;}
function newLife(reborn=false){const inherited={compassion:.52,fear:.38,curiosity:.72,ambition:.40,attachment:.34,resolve:.48};if(reborn)for(const e of soulEchoes)inherited[e.trait]=clamp(inherited[e.trait]+e.delta);state={year:1,season:0,age:24,generation:(state?.generation||0)+1,alive:true,paused:false,speed:1,traits:inherited,morals:{selfOthers:.52,mercyJustice:.54,freedomOrder:.58,truthBelonging:.61,preserveChange:.49},memory:[],bonds:0,scars:0,hope:.56,health:1,settlement:.08,water:.72,chapter:'Awakening beside the dead machine'};logStory(reborn?rebirthText():'A traveler wakes in wet grass beneath a pale sky. Behind them, a machine large enough to have once carried a village sits silent and half-buried. They remember their name—Mara—but almost nothing else.');updateUI();updateWorld();}
const events=[
{id:'stranger',title:'A stranger beneath the mill',score:s=>.8+pressures.community*.8+s.traits.compassion*.7+pressures.danger*.25+(1-pressures.abundance)*.45,resolve:s=>{const help=sig(2.2*s.traits.compassion+1.4*s.morals.selfOthers+pressures.community-.9*s.traits.fear-1.15);if(Math.random()<help){s.bonds++;s.traits.compassion=clamp(s.traits.compassion+.035);s.morals.selfOthers=clamp(s.morals.selfOthers+.03);s.memory.push('sheltered a stranger');return 'At the abandoned mill, Mara finds a stranger sleeping beneath rusted metal. Food is scarce. She divides what she has anyway. By morning the stranger has a name—Eren—and the road no longer feels entirely empty.';}s.traits.fear=clamp(s.traits.fear+.04);s.morals.selfOthers=clamp(s.morals.selfOthers-.025);s.memory.push('turned away a stranger');return 'At the abandoned mill, Mara finds a stranger asleep beneath rusted metal. She watches from the trees until he wakes, then leaves without speaking. That night she eats well and sleeps badly.';}},
{id:'storm',title:'The black rain',score:s=>.75+pressures.change*.8+pressures.mystery*.65+pressures.danger*.4,resolve:s=>{s.health=clamp(s.health-.05*pressures.danger);s.traits.resolve=clamp(s.traits.resolve+.03);s.memory.push('survived the black rain');return 'Clouds gather before noon, too quickly and from every direction. The rain that follows is warm, dark, and faintly metallic. Mara shelters inside the dead machine and hears something moving in its sealed lower chambers.';}},
{id:'garden',title:'Seeds in the ash',score:s=>.65+pressures.abundance*.55+pressures.community*.45+s.traits.attachment*.45+(1-pressures.danger)*.3,resolve:s=>{s.settlement=clamp(s.settlement+.08);s.hope=clamp(s.hope+.06);s.traits.attachment=clamp(s.traits.attachment+.04);s.memory.push('planted the ash garden');return 'Near the river, Mara discovers a patch of ash where tiny green shoots have survived. She marks the place with stones and begins tending it. The Hollow acquires its first deliberate future.';}},
{id:'beacon',title:'The sleeping beacon',score:s=>.5+pressures.technology*.9+pressures.mystery*.75+s.traits.curiosity*.7,resolve:s=>{if(Math.random()<sig(s.traits.curiosity+pressures.technology-s.traits.fear)){s.traits.curiosity=clamp(s.traits.curiosity+.04);s.morals.preserveChange=clamp(s.morals.preserveChange+.03);s.memory.push('woke the beacon');return 'The ruined tower emits a tone for exactly thirteen seconds. Mara climbs it despite every instinct telling her not to. At the top she finds a blue light pulsing in time with her heartbeat.';}s.traits.fear=clamp(s.traits.fear+.03);return 'A blue light flickers atop the ruined tower. Mara watches it from the valley floor until it goes dark. She tells herself that restraint and cowardice are not the same thing.';}},
{id:'raid',title:'Footprints at the hearth',score:s=>.35+pressures.danger*1.2+(1-pressures.community)*.35+(1-pressures.abundance)*.4,resolve:s=>{const stand=sig(s.traits.resolve+s.traits.attachment+pressures.community-s.traits.fear-.45);if(Math.random()<stand){s.traits.resolve=clamp(s.traits.resolve+.05);s.scars++;s.settlement=clamp(s.settlement-.03);s.memory.push('defended the hearth');return 'Unknown footprints circle the hearth before dawn. Mara stays. When the strangers finally emerge, words fail before courage does. By sunrise the Hollow still belongs to those who slept there, though Mara carries a new scar.';}s.settlement=clamp(s.settlement-.07);s.traits.fear=clamp(s.traits.fear+.05);return 'Unknown footprints circle the hearth before dawn. Mara leaves before the strangers arrive. When she returns days later, the stores are gone and the firepit has been kicked apart.';}},
{id:'child',title:'A question with no safe answer',score:s=>.2+pressures.community*.8+s.bonds*.18+s.traits.attachment*.4,resolve:s=>{s.bonds++;s.morals.truthBelonging=clamp(s.morals.truthBelonging+(Math.random()-.45)*.08);s.memory.push('became responsible for another life');return 'A child from a passing family asks Mara why the old world ended. She realizes that the answer she gives may matter less than the fact that the child believes she knows. Responsibility arrives quietly, disguised as a question.';}},
{id:'road',title:'The road beyond the ridge',score:s=>.3+pressures.freedom*.7+pressures.change*.6+s.traits.curiosity*.5+s.traits.ambition*.4,resolve:s=>{s.traits.ambition=clamp(s.traits.ambition+.025);s.morals.freedomOrder=clamp(s.morals.freedomOrder+.025);s.memory.push('crossed the ridge');return 'Mara follows the old road beyond the ridge and sees lights where no settlement should be. She returns before dark, but the shape of the world has changed simply because she now knows the Hollow is not alone.';}}
];
function weightedEvent(){const bag=[];for(const e of events){const w=Math.max(.05,e.score(state));for(let i=0;i<Math.ceil(w*4);i++)bag.push(e)}return choice(bag)}
function drift(){const t=state.traits;t.fear=clamp(t.fear+(pressures.danger-.5)*.018);t.curiosity=clamp(t.curiosity+(pressures.mystery-.5)*.012);t.attachment=clamp(t.attachment+(pressures.community-.5)*.014);t.ambition=clamp(t.ambition+(pressures.change-.5)*.01);t.resolve=clamp(t.resolve+(pressures.danger+.3*pressures.change-.55)*.008);state.health=clamp(state.health+(pressures.abundance-.48)*.018-pressures.danger*.008);state.water=clamp(state.water+(pressures.abundance-.5)*.01);}
function turnWheel(){if(!state.alive)return;drift();const e=weightedEvent();state.chapter=e.title;logStory(e.resolve(state));state.season=(state.season+1)%4;if(state.season===0){state.year++;state.age++;}if(state.health<=.05||state.age>72){state.alive=false;soulEchoes=[{trait:'fear',delta:(Math.random()-.5)*.12,phrase:'the sound of rain causes an unreasonable ache behind the ribs'},{trait:'curiosity',delta:.06,phrase:'the ruined tower feels less like a discovery than a return'}].slice(0,1+Math.floor(Math.random()*2));flashOmen('A life closes');}updateUI();updateWorld();}
function updateUI(){document.getElementById('dateLine').textContent=`Year ${state.year} · ${seasons[state.season]}`;document.getElementById('chapter').textContent=state.chapter;document.getElementById('age').textContent=`Age ${state.age}`;document.getElementById('generation').textContent=`Life ${['I','II','III','IV','V','VI','VII','VIII','IX','X'][state.generation-1]||state.generation}`;document.getElementById('place').textContent=state.settlement>.58?'The Settlement':state.settlement>.28?'The New Hearth':'The Hollow';const tr=document.getElementById('traits');tr.innerHTML='';Object.entries(state.traits).forEach(([k,v])=>tr.insertAdjacentHTML('beforeend',`<div class="pill"><b>${k}</b><span>${Math.round(v*100)}</span></div>`));document.getElementById('soulLine').textContent=state.memory.length?`Memory: ${state.memory.slice(-2).join(' · ')}`:'No remembered deeds yet.';const m=document.getElementById('morals');m.innerHTML='';const names={selfOthers:['Self','Others'],mercyJustice:['Mercy','Justice'],freedomOrder:['Freedom','Order'],truthBelonging:['Truth','Belonging'],preserveChange:['Preserve','Change']};Object.entries(state.morals).forEach(([k,v])=>m.insertAdjacentHTML('beforeend',`<div class="labelrow"><span>${names[k][0]}</span><span class="val">${names[k][1]}</span></div><div class="moralbar"><i style="width:${v*100}%"></i></div>`));document.getElementById('pauseBtn').textContent=state.paused?'Resume':'Pause';}
const sliders=document.getElementById('sliders');Object.keys(pressures).forEach(k=>{sliders.insertAdjacentHTML('beforeend',`<div class="labelrow"><span>${labels[k]}</span><span class="val" id="${k}v">${Math.round(pressures[k]*100)}</span></div><input aria-label="${labels[k]}" id="${k}" type="range" min="0" max="100" value="${pressures[k]*100}">`);document.getElementById(k).oninput=e=>{pressures[k]=+e.target.value/100;document.getElementById(k+'v').textContent=e.target.value;updateWorld();};});
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x10151a,.025);const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,200);camera.position.set(16,12,19);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.getElementById('world').appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=12;controls.maxDistance=42;controls.maxPolarAngle=Math.PI*.48;controls.target.set(0,2,0);
scene.add(new THREE.HemisphereLight(0xbfd4d2,0x20211f,1.15));const sun=new THREE.DirectionalLight(0xffe7c7,2.2);sun.position.set(-8,15,9);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.CylinderGeometry(10,11,1,64),new THREE.MeshStandardMaterial({color:0x324234,roughness:1}));ground.position.y=-.5;ground.receiveShadow=true;scene.add(ground);const water=new THREE.Mesh(new THREE.CircleGeometry(4.4,64),new THREE.MeshStandardMaterial({color:0x304b57,roughness:.25,metalness:.1,transparent:true,opacity:.82}));water.rotation.x=-Math.PI/2;water.position.set(-4,.04,3);scene.add(water);const machine=new THREE.Group();for(let i=0;i<4;i++){const part=new THREE.Mesh(new THREE.BoxGeometry(3.4-i*.35,1.1,1.6),new THREE.MeshStandardMaterial({color:i%2?0x2d3337:0x414547,roughness:.8,metalness:.55}));part.position.set(3.8+i*.22,.55+i*.7,-2.1+i*.12);part.rotation.y=-.25;part.castShadow=true;machine.add(part)}scene.add(machine);const tower=new THREE.Group();for(let i=0;i<5;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(1.5-i*.12,.75,1.5-i*.12),new THREE.MeshStandardMaterial({color:0x49453d,roughness:.92}));b.position.set(-5,.4+i*.74,-3.8);b.rotation.y=i*.11;tower.add(b)}const beaconMat=new THREE.MeshStandardMaterial({color:0x6abde2,emissive:0x286e99,emissiveIntensity:1.6});const beacon=new THREE.Mesh(new THREE.SphereGeometry(.18,16,12),beaconMat);beacon.position.set(-5,4.15,-3.8);tower.add(beacon);scene.add(tower);const trees=[];for(let i=0;i<30;i++){const a=Math.random()*Math.PI*2,r=5+Math.random()*5;const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.09,.14,.9,7),new THREE.MeshStandardMaterial({color:0x514538}));trunk.position.y=.45;const crown=new THREE.Mesh(new THREE.ConeGeometry(.55+Math.random()*.35,1.8+Math.random(),7),new THREE.MeshStandardMaterial({color:0x263a2b}));crown.position.y=1.6;g.add(trunk,crown);g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);g.scale.setScalar(.75+Math.random()*.75);scene.add(g);trees.push(g)}
function humanoid(){const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:0x8a7763,roughness:.8}),cloth=new THREE.MeshStandardMaterial({color:0x3f5960,roughness:.9});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.28,.9,4,10),cloth);body.position.y=1.15;const head=new THREE.Mesh(new THREE.SphereGeometry(.24,16,12),mat);head.position.y=1.95;g.add(body,head);for(const x of[-.17,.17]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.085,.65,3,8),cloth);leg.position.set(x,.45,0);g.add(leg)}return g}const mara=humanoid();mara.position.set(0,0,.8);mara.scale.setScalar(1.15);scene.add(mara);const homes=[];function makeHome(i){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(1.25,.75,1),new THREE.MeshStandardMaterial({color:0x635649,roughness:1}));b.position.y=.38;const roof=new THREE.Mesh(new THREE.ConeGeometry(.95,.65,4),new THREE.MeshStandardMaterial({color:0x3b3029,roughness:1}));roof.position.y=1.05;roof.rotation.y=Math.PI/4;g.add(b,roof);const a=i*.9+1.5,r=2.2+(i%3)*.85;g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);g.visible=false;scene.add(g);homes.push(g)}for(let i=0;i<9;i++)makeHome(i);
function updateWorld(){if(!state)return;scene.fog.density=lerp(.012,.055,pressures.mystery*.65+pressures.danger*.35);ground.material.color.setHSL(.29,lerp(.18,.46,pressures.abundance),lerp(.17,.29,pressures.abundance));water.scale.setScalar(lerp(.65,1.1,state.water));sun.intensity=lerp(.8,2.8,pressures.abundance*(1-pressures.danger*.3));beacon.material.emissiveIntensity=lerp(.2,4,pressures.technology*pressures.mystery);trees.forEach((t,i)=>t.scale.y=lerp(.65,1.35,pressures.abundance)*(1+(i%4)*.03));homes.forEach((h,i)=>h.visible=i<Math.floor(state.settlement*10));mara.rotation.z=(state.health<.35?.08:0);}
let last=0,acc=0;function animate(t){requestAnimationFrame(animate);const dt=Math.min(.05,(t-last)/1000||0);last=t;controls.update();if(state&&!state.paused&&state.alive){acc+=dt*state.speed;if(acc>7){acc=0;turnWheel()}}mara.position.y=.03+Math.sin(t*.0015)*.025;mara.rotation.y=Math.sin(t*.0003)*.2;beacon.rotation.y+=dt;renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.getElementById('pauseBtn').onclick=()=>{state.paused=!state.paused;updateUI()};document.getElementById('speedBtn').onclick=e=>{speedIndex=(speedIndex+1)%speeds.length;state.speed=speeds[speedIndex];e.target.textContent=`${state.speed}× Time`};document.getElementById('nudgeBtn').onclick=()=>turnWheel();document.getElementById('rebirthBtn').onclick=()=>{if(state.alive){soulEchoes=[{trait:'attachment',delta:state.traits.attachment>.55?.05:-.02,phrase:'the sight of the river feels painfully intimate'},{trait:'resolve',delta:state.traits.resolve>.6?.05:0,phrase:'an old scar aches on skin that has never been wounded'}];}flashOmen('The world remembers');newLife(true)};newLife(false);requestAnimationFrame(animate);
</script>
</body>
</html>'''

components.html(HTML, height=900, scrolling=False)
