import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(page_title="The Turning", page_icon="◌", layout="wide", initial_sidebar_state="collapsed")

st.markdown("""
<style>
.stApp { background: #090b0f; }
[data-testid="stHeader"] { background: rgba(0,0,0,0); }
.block-container { padding: 0.75rem 1rem 1rem; max-width: 1800px; }
iframe { border-radius: 18px; }
</style>
""", unsafe_allow_html=True)

HTML = r'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>The Turning</title>
<style>
:root{--bg:#080a0d;--panel:rgba(12,15,20,.82);--line:rgba(255,255,255,.10);--text:#ebe8df;--muted:#aaa79f}
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}
#app{height:100vh;position:relative;background:radial-gradient(circle at 50% 30%,#162022 0,#090b0e 50%,#060709 100%)}
#world{position:absolute;inset:0}.brand{position:absolute;top:22px;left:24px;z-index:10;pointer-events:none}.brand h1{font-family:Georgia,serif;font-weight:500;letter-spacing:.08em;text-transform:uppercase;margin:0;font-size:28px}.brand .sub{font-size:11px;letter-spacing:.23em;text-transform:uppercase;color:var(--muted);margin-top:5px}
.hud{position:absolute;right:18px;top:18px;width:315px;max-height:calc(100vh - 36px);overflow:auto;z-index:12;background:var(--panel);backdrop-filter:blur(16px);border:1px solid var(--line);border-radius:18px;padding:15px}.section{padding:0 1px 14px;border-bottom:1px solid var(--line);margin-bottom:14px}.section:last-child{border:0;margin:0}.eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.2em;color:#9c9a93;margin-bottom:7px}.labelrow{display:flex;justify-content:space-between;align-items:center;margin:8px 0 4px}.labelrow span:first-child{font-size:12px}.val{font:11px ui-monospace,monospace;color:#bbb}input[type=range]{width:100%;accent-color:#9fc3ad}.pills{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.pill{padding:7px 8px;border:1px solid var(--line);border-radius:10px;background:rgba(255,255,255,.025)}.pill b{display:block;font-size:10px;text-transform:uppercase;color:#9e9f9a}.pill span{font:12px ui-monospace,monospace}.actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.btn{border:1px solid var(--line);background:rgba(255,255,255,.055);color:var(--text);border-radius:10px;padding:9px 10px;font-size:11px;text-transform:uppercase;cursor:pointer}.btn.primary{background:rgba(140,190,160,.12)}
.chronicle{position:absolute;left:22px;bottom:20px;width:min(620px,calc(100vw - 390px));z-index:11;background:linear-gradient(180deg,rgba(10,12,15,.50),rgba(8,10,13,.86));backdrop-filter:blur(12px);border:1px solid var(--line);border-radius:18px;padding:16px 18px}.chapter{font:500 19px Georgia,serif;margin-bottom:8px}.story{font:15px/1.55 Georgia,serif;color:#ddd9d0;min-height:72px}.meta{display:flex;gap:12px;margin-top:10px;font:10px ui-monospace,monospace;color:#98958e;text-transform:uppercase}.moralbar{height:5px;background:#202329;border-radius:999px;overflow:hidden;margin:4px 0 8px}.moralbar i{display:block;height:100%;background:linear-gradient(90deg,#b28c69,#b9d7c1)}.soul{font:12px/1.45 Georgia,serif;color:#bcb8ae;font-style:italic;margin-top:6px}#omen{position:absolute;left:50%;top:20%;transform:translate(-50%,-50%);z-index:9;font:500 15px Georgia,serif;letter-spacing:.12em;text-transform:uppercase;color:#f2e5c9;opacity:0;transition:opacity .6s;pointer-events:none}
</style>
</head>
<body>
<div id="app">
<div id="world"></div>
<div class="brand"><h1>The Turning</h1><div class="sub">A life shaped by pressure, memory & chance</div></div>
<div id="omen"></div>
<div class="chronicle"><div class="eyebrow" id="dateLine">Year 1 · Early Spring</div><div class="chapter" id="chapter">Awakening beside the dead machine</div><div class="story" id="story">A traveler wakes in wet grass beneath a pale sky. Behind them, a machine large enough to have once carried a village sits silent and half-buried. They remember their name—Mara—but almost nothing else.</div><div class="meta"><span id="age">Age 24</span><span id="place">The Hollow</span><span id="generation">Life I</span></div></div>
<aside class="hud">
<div class="section"><div class="eyebrow">World Pressures</div><div id="sliders"></div></div>
<div class="section"><div class="eyebrow">Inner Weather</div><div class="pills" id="traits"></div><div class="soul" id="soulLine"></div></div>
<div class="section"><div class="eyebrow">Moral Tensions</div><div id="morals"></div></div>
<div class="section"><div class="eyebrow">Time & Retelling</div><div class="actions"><button class="btn primary" id="pauseBtn">Pause</button><button class="btn" id="speedBtn">1× Time</button><button class="btn" id="nudgeBtn">Turn the Wheel</button><button class="btn" id="rebirthBtn">Rebirth</button></div></div>
</aside></div>
<script type="module">
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/controls/OrbitControls.js';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)), choice=a=>a[Math.floor(Math.random()*a.length)], lerp=(a,b,t)=>a+(b-a)*t, sig=x=>1/(1+Math.exp(-x));
const pressures={abundance:.55,danger:.36,community:.44,mystery:.68,change:.48,freedom:.62,technology:.24,fate:.50};
const labels={abundance:'Abundance',danger:'Danger',community:'Community',mystery:'Mystery',change:'Change',freedom:'Freedom',technology:'Technology',fate:'Fate'};
let soulEchoes=[], state, speedIndex=0; const speeds=[1,2,4], seasons=['Early Spring','High Summer','Late Autumn','Deep Winter'];
function logStory(text){document.getElementById('story').textContent=text;}
function flashOmen(t){const o=document.getElementById('omen');o.textContent=t;o.style.opacity=1;setTimeout(()=>o.style.opacity=0,1500)}
function rebirthText(){if(!soulEchoes.length)return 'The world folds inward and begins again. Mara wakes beside the dead machine with no memory of another life, though the morning feels strangely familiar.';const e=choice(soulEchoes);return `The world begins again. Mara wakes beside the dead machine. Nothing of the former life can be recalled, yet ${e.phrase}.`;}
function newLife(reborn=false){const inherited={compassion:.52,fear:.38,curiosity:.72,ambition:.40,attachment:.34,resolve:.48};if(reborn)for(const e of soulEchoes)inherited[e.trait]=clamp(inherited[e.trait]+e.delta);state={year:1,season:0,age:24,generation:(state?.generation||0)+1,alive:true,paused:false,speed:1,traits:inherited,morals:{selfOthers:.52,mercyJustice:.54,freedomOrder:.58,truthBelonging:.61,preserveChange:.49},memory:[],bonds:0,scars:0,hope:.56,health:1,settlement:.08,water:.72,chapter:'Awakening beside the dead machine'};logStory(reborn?rebirthText():'A traveler wakes in wet grass beneath a pale sky. Behind them, a machine large enough to have once carried a village sits silent and half-buried. They remember their name—Mara—but almost nothing else.');updateUI();updateWorld();}
const events=[
{id:'stranger',title:'A stranger beneath the mill',score:s=>.8+pressures.community*.8+s.traits.compassion*.7+pressures.danger*.25+(1-pressures.abundance)*.45,resolve:s=>{const help=sig(2.2*s.traits.compassion+1.4*s.morals.selfOthers+pressures.community-.9*s.traits.fear-1.15);if(Math.random()<help){s.bonds++;s.traits.compassion=clamp(s.traits.compassion+.035);s.morals.selfOthers=clamp(s.morals.selfOthers+.03);s.memory.push('sheltered a stranger');return 'At the abandoned mill, Mara finds a stranger sleeping beneath rusted metal. Food is scarce. She divides what she has anyway. By morning the stranger has a name—Eren—and the road no longer feels entirely empty.';}s.traits.fear=clamp(s.traits.fear+.04);s.morals.selfOthers=clamp(s.morals.selfOthers-.025);s.memory.push('turned away a stranger');return 'At the abandoned mill, Mara finds a stranger asleep beneath rusted metal. She watches from the trees until he wakes, then leaves without speaking. That night she eats well and sleeps badly.';}},
{id:'storm',title:'The black rain',score:s=>.75+pressures.change*.8+pressures.mystery*.65+pressures.danger*.4,resolve:s=>{s.health=clamp(s.health-.05*pressures.danger);s.traits.resolve=clamp(s.traits.resolve+.03);s.memory.push('survived the black rain');return 'Clouds gather before noon, too quickly and from every direction. The rain that follows is warm, dark, and faintly metallic. Mara shelters inside the dead machine and hears something moving in its sealed lower chambers.';}},
{id:'garden',title:'Seeds in the ash',score:s=>.65+pressures.abundance*.55+pressures.community*.45+s.traits.attachment*.45+(1-pressures.danger)*.3,resolve:s=>{s.settlement=clamp(s.settlement+.08);s.hope=clamp(s.hope+.06);s.traits.attachment=clamp(s.traits.attachment+.04);s.memory.push('planted the ash garden');return 'Near the river, Mara discovers a patch of ash where tiny green shoots have survived. She marks the place with stones and begins tending it. The Hollow acquires its first deliberate future.';}},
{id:'beacon',title:'The sleeping beacon',score:s=>.5+pressures.technology*.9+pressures.mystery*.75+s.traits.curiosity*.7,resolve:s=>{if(Math.random()<sig(s.traits.curiosity+pressures.technology-s.traits.fear)){s.traits.curiosity=clamp(s.traits.curiosity+.04);s.morals.preserveChange=clamp(s.morals.preserveChange+.03);s.memory.push('woke the beacon');return 'The ruined tower emits a tone for exactly thirteen seconds. Mara climbs it despite every instinct telling her not to. At the top she finds a blue light pulsing in time with her heartbeat.';}s.traits.fear=clamp(s.traits.fear+.03);return 'A blue light flickers atop the ruined tower. Mara watches it from the valley floor until it goes dark. She tells herself that restraint and cowardice are not the same thing.';}},
{id:'raid',title:'Footprints at the hearth',score:s=>.35+pressures.danger*1.2+(1-pressures.community)*.35+(1-pressures.abundance)*.4,resolve:s=>{const stand=sig(s.traits.resolve+s.traits.attachment+pressures.community-s.traits.fear-.45);if(Math.random()<stand){s.traits.resolve=clamp(s.traits.resolve+.05);s.scars++;s.settlement=clamp(s.settlement-.03);s.memory.push('defended the hearth');return 'Unknown footprints circle the hearth before dawn. Mara stays. When the strangers finally emerge, words fail before courage does. By sunrise the Hollow still belongs to those who slept there, though Mara carries a new scar.';}s.settlement=clamp(s.settlement-.07);s.traits.fear=clamp(s.traits.fear+.05);return 'Unknown footprints circle the hearth before dawn. Mara leaves before the strangers arrive. When she returns days later, the stores are gone and the firepit has been kicked apart.';}},
{id:'child',title:'A question with no safe answer',score:s=>.2+pressures.community*.8+s.bonds*.18+s.traits.attachment*.4,resolve:s=>{s.bonds++;s.morals.truthBelonging=clamp(s.morals.truthBelonging+(Math.random()-.45)*.08);s.memory.push('became responsible for another life');return 'A child from a passing family asks Mara why the old world ended. She realizes that the answer she gives may matter less than the fact that the child believes she knows. Responsibility arrives quietly, disguised as a question.';}},
{id:'road',title:'The road beyond the ridge',score:s=>.3+pressures.freedom*.7+pressures.change*.6+s.traits.curiosity*.5+s.traits.ambition*.4,resolve:s=>{s.traits.ambition=clamp(s.traits.ambition+.025);s.morals.freedomOrder=clamp(s.morals.freedomOrder+.025);s.memory.push('crossed the ridge');return 'Mara follows the old road beyond the ridge and sees lights where no settlement should be. She returns before dark, but the shape of the world has changed simply because she now knows the Hollow is not alone.';}}
];
function weightedEvent(){const bag=[];for(const e of events){const w=Math.max(.05,e.score(state));for(let i=0;i<Math.ceil(w*4);i++)bag.push(e)}return choice(bag)}
function drift(){const t=state.traits;t.fear=clamp(t.fear+(pressures.danger-.5)*.018);t.curiosity=clamp(t.curiosity+(pressures.mystery-.5)*.012);t.attachment=clamp(t.attachment+(pressures.community-.5)*.014);t.ambition=clamp(t.ambition+(pressures.change-.5)*.01);t.resolve=clamp(t.resolve+(pressures.danger+.3*pressures.change-.55)*.008);state.health=clamp(state.health+(pressures.abundance-.48)*.018-pressures.danger*.008);state.water=clamp(state.water+(pressures.abundance-.5)*.01);}
function turnWheel(){if(!state.alive)return;drift();const e=weightedEvent();state.chapter=e.title;logStory(e.resolve(state));state.season=(state.season+1)%4;if(state.season===0){state.year++;state.age++;}if(state.health<=.05||state.age>72){state.alive=false;soulEchoes=[{trait:'fear',delta:(Math.random()-.5)*.12,phrase:'the sound of rain causes an unreasonable ache behind the ribs'},{trait:'curiosity',delta:.06,phrase:'the ruined tower feels less like a discovery than a return'}].slice(0,1+Math.floor(Math.random()*2));flashOmen('A life closes');}updateUI();updateWorld();}
function updateUI(){document.getElementById('dateLine').textContent=`Year ${state.year} · ${seasons[state.season]}`;document.getElementById('chapter').textContent=state.chapter;document.getElementById('age').textContent=`Age ${state.age}`;document.getElementById('generation').textContent=`Life ${['I','II','III','IV','V','VI','VII','VIII','IX','X'][state.generation-1]||state.generation}`;document.getElementById('place').textContent=state.settlement>.58?'The Settlement':state.settlement>.28?'The New Hearth':'The Hollow';const tr=document.getElementById('traits');tr.innerHTML='';Object.entries(state.traits).forEach(([k,v])=>tr.insertAdjacentHTML('beforeend',`<div class="pill"><b>${k}</b><span>${Math.round(v*100)}</span></div>`));const defs=[['selfOthers','Self','Others'],['mercyJustice','Justice','Mercy'],['freedomOrder','Order','Freedom'],['truthBelonging','Belonging','Truth'],['preserveChange','Preserve','Change']];const m=document.getElementById('morals');m.innerHTML='';defs.forEach(([k,l,r])=>m.insertAdjacentHTML('beforeend',`<div class="labelrow"><span>${l}</span><span>${r}</span></div><div class="moralbar"><i style="width:${Math.round(state.morals[k]*100)}%"></i></div>`));const d=[];if(state.traits.compassion>.66)d.push('tender toward strangers');if(state.traits.fear>.62)d.push('watchful');if(state.traits.curiosity>.68)d.push('drawn toward unanswered things');if(state.traits.resolve>.65)d.push('difficult to move once decided');if(state.traits.attachment>.62)d.push('deeply rooted in people and place');document.getElementById('soulLine').textContent=`Mara is ${d.length?d.join(', '):'still becoming someone the world can name'}.`;}
const sliderHost=document.getElementById('sliders');Object.keys(pressures).forEach(k=>{const w=document.createElement('div');w.innerHTML=`<div class="labelrow"><span>${labels[k]}</span><span class="val" id="v-${k}">${Math.round(pressures[k]*100)}</span></div><input id="s-${k}" type="range" min="0" max="100" value="${pressures[k]*100}">`;sliderHost.appendChild(w);w.querySelector('input').addEventListener('input',e=>{pressures[k]=+e.target.value/100;document.getElementById('v-'+k).textContent=e.target.value;updateWorld();});});
document.getElementById('pauseBtn').onclick=()=>{state.paused=!state.paused;document.getElementById('pauseBtn').textContent=state.paused?'Resume':'Pause'};document.getElementById('speedBtn').onclick=()=>{speedIndex=(speedIndex+1)%speeds.length;state.speed=speeds[speedIndex];document.getElementById('speedBtn').textContent=state.speed+'× Time'};document.getElementById('nudgeBtn').onclick=turnWheel;document.getElementById('rebirthBtn').onclick=()=>newLife(true);
const host=document.getElementById('world'),scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x0f1618,.028);const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,250);camera.position.set(18,13,22);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=12;controls.maxDistance=42;controls.target.set(0,2,0);
const hemi=new THREE.HemisphereLight(0xa9c8cc,0x2d261f,1.9);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe2b6,3.2);sun.position.set(-10,18,6);scene.add(sun);const groundMat=new THREE.MeshStandardMaterial({color:0x26352d,roughness:1}),ground=new THREE.Mesh(new THREE.CylinderGeometry(12,13,1.1,64),groundMat);ground.position.y=-.75;scene.add(ground);const water=new THREE.Mesh(new THREE.CircleGeometry(5.2,48),new THREE.MeshPhysicalMaterial({color:0x365d63,roughness:.25,transparent:true,opacity:.72}));water.rotation.x=-Math.PI/2;water.position.set(-5,.02,2);scene.add(water);
const machine=new THREE.Mesh(new THREE.BoxGeometry(5,2.2,2.5),new THREE.MeshStandardMaterial({color:0x34383a,roughness:.78,metalness:.55}));machine.rotation.z=-.09;machine.position.set(4,.8,-3);scene.add(machine);const tower=new THREE.Mesh(new THREE.CylinderGeometry(.65,1.1,7,6),new THREE.MeshStandardMaterial({color:0x3b403f,roughness:.9}));tower.position.set(-6,3.1,-5);scene.add(tower);const beacon=new THREE.PointLight(0x78b7ff,0,8,2);beacon.position.set(-6,6.7,-5);scene.add(beacon);
const huts=[];function hut(x,z){const g=new THREE.Group(),wall=new THREE.Mesh(new THREE.CylinderGeometry(.8,.9,1.25,6),new THREE.MeshStandardMaterial({color:0x786553})),roof=new THREE.Mesh(new THREE.ConeGeometry(1.08,.9,6),new THREE.MeshStandardMaterial({color:0x493d32}));wall.position.y=.62;roof.position.y=1.7;g.add(wall,roof);g.position.set(x,0,z);g.scale.setScalar(.001);scene.add(g);huts.push(g)}[[1,4],[3,4.8],[4.6,3.5],[2.2,6.2],[5.4,5.7],[-.4,5.4]].forEach(p=>hut(...p));
for(let i=0;i<28;i++){const a=Math.random()*Math.PI*2,r=7+Math.random()*4,g=new THREE.Group(),trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12,.18,1.8,7),new THREE.MeshStandardMaterial({color:0x4b3529})),crown=new THREE.Mesh(new THREE.ConeGeometry(.7,2.4,7),new THREE.MeshStandardMaterial({color:0x304d38}));trunk.position.y=.9;crown.position.y=2.45;g.add(trunk,crown);g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);g.scale.setScalar(.8+Math.random()*.5);scene.add(g)}
const person=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color:0x76664f}),skin=new THREE.MeshStandardMaterial({color:0x9f765d});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.85,4,8),cloth);torso.position.y=1.45;const head=new THREE.Mesh(new THREE.SphereGeometry(.31,16,12),skin);head.position.y=2.35;person.add(torso,head);person.position.set(.3,0,.2);scene.add(person);const fireLight=new THREE.PointLight(0xff8a42,2,7,2);fireLight.position.set(1.7,.8,2.6);scene.add(fireLight);const fire=new THREE.Mesh(new THREE.ConeGeometry(.25,.8,8),new THREE.MeshBasicMaterial({color:0xffa24e}));fire.position.set(1.7,.45,2.6);scene.add(fire);
function updateWorld(){if(!state)return;scene.fog.density=lerp(.012,.055,pressures.mystery*.55+pressures.danger*.35);water.scale.setScalar(.62+state.water*.5);beacon.intensity=pressures.technology*pressures.mystery*3.5;const dry=1-pressures.abundance;groundMat.color.setHSL(.27-dry*.14,.16+pressures.abundance*.16,.18+pressures.abundance*.05);huts.forEach((h,i)=>{const threshold=.18+i*.10;h.scale.setScalar(state.settlement>threshold?1:.001)});}
let last=performance.now(),acc=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min(.05,(now-last)/1000);last=now;controls.update();acc+=dt;person.scale.y=1+Math.sin(now*.002)*.012;person.rotation.y=Math.sin(now*.00035)*.45;fire.scale.y=.82+Math.sin(now*.015)*.25;fireLight.intensity=1.5+Math.random()*1.2;if(state&&!state.paused&&state.alive&&acc>(8/state.speed)){acc=0;turnWheel()}renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});newLife(false);animate(performance.now());
</script></body></html>'''

components.html(HTML, height=900, scrolling=False)
