import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const choice=a=>a[Math.floor(Math.random()*a.length)];
const lerp=(a,b,t)=>a+(b-a)*t;
const sig=x=>1/(1+Math.exp(-x));
const pressures={abundance:.55,danger:.36,community:.44,mystery:.68,change:.48,freedom:.62,technology:.24,fate:.50};
const pressureLabels={abundance:'Abundance',danger:'Danger',community:'Community',mystery:'Mystery',change:'Change',freedom:'Freedom',technology:'Technology',fate:'Fate'};
const seasons=['Early Spring','High Summer','Late Autumn','Deep Winter'];
let soulEchoes=[],state;
const legacy={lives:0,echoStones:0,myths:[],relics:[],names:[]};

function hasMemory(fragment){return state.memory.some(x=>x.includes(fragment));}
function remember(key){if(!state.memory.includes(key))state.memory.push(key);}
function addHistory(title,text){state.history.unshift({year:state.year,season:seasons[state.season],title,text});state.history=state.history.slice(0,8);}
function mythify(seed){
  const variants={
    stranger:['The Guest Beneath Iron','The First Shared Bread','Eren at the Mill'],storm:['The Black Rain','The Night the Machine Breathed','Rain of Old Metal'],garden:['The Ash Garden','The First Green Promise','Mara and the Seed-Stones'],tower:['The Blue Eye on the Ridge','The Voice in the Tower','The Returning Light'],raiders:['The Standing at the Ridge','The Burned Roofs','The Scar of Dawn'],child:['The First Question','The Child Who Asked the Machine','The Story Before History'],machine:['The Eleven Seconds','The Machine That Knew Her Name','The Return Vector'],festival:['The Lantern Season','The Night of Three Strings','The Feast of Ordinary Days'],funeral:['The Stone Without a Body','The First Grave Song','The Empty Chair'],schism:['The Splitting Hearth','The Road of Two Fires','The Leaving'],invention:['The Wind-Wheel','The Bright Coil','The First Useful Lightning']
  };
  const list=variants[seed];if(!list)return;const name=choice(list);if(!state.myths.includes(name)){state.myths.push(name);legacy.myths.push(name);legacy.myths=[...new Set(legacy.myths)].slice(-12);state.lore=clamp(state.lore+.08);}
}
function maybeMyth(seed,chance=.18){const weight=chance+pressures.mystery*.18+state.lore*.2+Math.min(.2,state.population*.008);if(Math.random()<weight)mythify(seed);}

function newLife(reborn=false){
  const priorGeneration=state?.generation||0;const inherited={compassion:.52,fear:.38,curiosity:.72,ambition:.40,attachment:.34,resolve:.48};
  if(reborn)for(const e of soulEchoes)inherited[e.trait]=clamp(inherited[e.trait]+e.delta);
  state={year:1,season:0,age:24,generation:priorGeneration+1,alive:true,paused:false,speed:1,traits:inherited,morals:{selfOthers:.52,mercyJustice:.54,freedomOrder:.58,truthBelonging:.61,preserveChange:.49},memory:[],history:[],myths:[],bonds:0,scars:0,hope:.56,health:1,settlement:.08,ruins:.70,water:.72,population:1,food:.55,cohesion:.44,lore:reborn?Math.min(.22,legacy.myths.length*.018):0,damage:0,techAwake:0,eren:false,children:0,departed:0,chapter:'Awakening beside the dead machine',lastEvent:'awakening'};
  if(reborn){legacy.lives++;legacy.echoStones++;state.lore=clamp(state.lore+.04*legacy.echoStones);}const opening=reborn?rebirthText():'A traveler wakes in wet grass beneath a pale sky. Behind them, a machine large enough to have once carried a village sits silent and half-buried. They remember their name—Mara—but almost nothing else.';logStory(opening);addHistory(state.chapter,opening);updateUI();
}
function rebirthText(){if(!soulEchoes.length)return 'The world folds inward and begins again. Mara wakes beside the dead machine with no memory of another life, though the morning feels strangely familiar.';const echo=choice(soulEchoes);const myth=legacy.myths.length?` Somewhere nearby, people still tell a story called “${choice(legacy.myths)},” though she does not know why the title hurts.`:'';return `The world begins again. Mara wakes beside the dead machine. Nothing of the former life can be recalled, yet ${echo.phrase}.${myth}`;}

const events=[
{id:'stranger',title:'A stranger beneath the mill',base:.80,when:s=>!s.eren,score:s=>pressures.community*.8+s.traits.compassion*.7+pressures.danger*.18+(1-pressures.abundance)*.35,resolve:s=>{const help=sig(2.2*s.traits.compassion+1.2*s.morals.selfOthers+pressures.community-.9*s.traits.fear-1.1);if(Math.random()<help){s.eren=true;s.bonds++;s.population+=1;s.cohesion=clamp(s.cohesion+.08);s.traits.compassion=clamp(s.traits.compassion+.035);s.morals.selfOthers=clamp(s.morals.selfOthers+.03);remember('sheltered Eren beneath the mill');maybeMyth('stranger',.28);return 'At the abandoned mill, Mara finds a stranger sleeping beneath rusted metal. Food is not plentiful. She divides what she has anyway. By morning the stranger has a name—Eren—and the road no longer feels entirely empty.';}s.traits.fear=clamp(s.traits.fear+.04);s.cohesion=clamp(s.cohesion-.02);remember('turned away the stranger at the mill');return 'Mara finds a stranger asleep beneath rusted metal. She watches from the trees until he wakes, then leaves without speaking. That night she eats well and sleeps badly.';}},
{id:'storm',title:'The black rain',base:.72,score:s=>pressures.change*.8+pressures.mystery*.7+pressures.danger*.45,resolve:s=>{s.health=clamp(s.health-.03-.06*pressures.danger);s.damage=clamp(s.damage+.05+.08*pressures.change);s.traits.resolve=clamp(s.traits.resolve+.03);remember('survived the black rain');maybeMyth('storm',.32);return 'Clouds gather before noon, too quickly and from every direction. The rain is warm, dark, and faintly metallic. Mara shelters inside the dead machine while the settlement roofs hiss beneath it.';}},
{id:'garden',title:'Seeds in the ash',base:.68,when:s=>!hasMemory('ash garden'),score:s=>pressures.abundance*.7+pressures.community*.45+s.traits.attachment*.55+(1-pressures.danger)*.25,resolve:s=>{s.settlement=clamp(s.settlement+.09);s.food=clamp(s.food+.12);s.hope=clamp(s.hope+.07);s.traits.attachment=clamp(s.traits.attachment+.04);remember('planted the ash garden');maybeMyth('garden',.34);return 'Near the river, Mara discovers green shoots in a patch of ash. She fences the ground with broken antennae and plants every viable seed she owns. The Hollow acquires its first deliberate future.';}},
{id:'tower',title:'The light in the tower',base:.62,score:s=>pressures.technology*.8+pressures.mystery*.85+s.traits.curiosity*.65,resolve:s=>{const enter=Math.random()<sig(s.traits.curiosity*2-s.traits.fear+pressures.fate-.8);if(enter){s.techAwake=clamp(s.techAwake+.15);s.lore=clamp(s.lore+.08);s.traits.curiosity=clamp(s.traits.curiosity+.04);remember('entered the lit tower');maybeMyth('tower',.42);return 'A dead tower on the western ridge shows a single blue light. Mara climbs after sunset. Inside, a machine speaks one sentence in her own voice: “You have been here before.”';}s.traits.fear=clamp(s.traits.fear+.025);return 'A single blue light appears in the dead western tower. Mara watches until dawn but does not climb. Relief arrives with sunrise, and she distrusts it.';}},
{id:'dispute',title:'Bread and judgment',base:.60,when:s=>s.population>=5,score:s=>pressures.community*.7+(1-s.food)*.9+s.population*.018,resolve:s=>{const mercy=s.morals.mercyJustice+s.traits.compassion*.45-s.traits.fear*.22;if(mercy>.7){s.morals.mercyJustice=clamp(s.morals.mercyJustice+.04);s.cohesion=clamp(s.cohesion+.06);s.food=clamp(s.food-.05);return 'Two families accuse one another of stealing winter flour. Mara refuses punishment and divides the remaining stores publicly. Nobody is satisfied, but nobody leaves.';}s.morals.mercyJustice=clamp(s.morals.mercyJustice-.04);s.cohesion=clamp(s.cohesion-.06);s.departed++;s.population=Math.max(1,s.population-1);return 'Two families accuse one another of stealing winter flour. Mara orders the suspected thief expelled. The stores last. So does the memory of the sentence.';}},
{id:'raiders',title:'Smoke beyond the ridge',base:.54,when:s=>s.population>=3,score:s=>pressures.danger*1.35+s.settlement*.5+(1-s.cohesion)*.45,resolve:s=>{const stand=sig(s.traits.resolve*1.45+s.traits.attachment+s.cohesion-s.traits.fear-.75);if(Math.random()<stand){s.scars++;s.health=clamp(s.health-.10);s.damage=clamp(s.damage+.12);s.cohesion=clamp(s.cohesion+.06);s.population+=Math.random()<.45?2:0;s.traits.resolve=clamp(s.traits.resolve+.05);remember('stood at the ridge');maybeMyth('raiders',.48);return 'Smoke rises beyond the ridge and figures appear on the old road. Mara stays. The fight is brief, ugly, and enough. By dawn she has another scar—and strangers who fought beside her now call this place home.';}s.damage=clamp(s.damage+.28);s.settlement=clamp(s.settlement-.10);s.cohesion=clamp(s.cohesion-.09);s.population=Math.max(1,s.population-Math.max(1,Math.floor(Math.random()*3)));remember('fled the ridge');return 'Smoke rises beyond the ridge. Mara leaves before the figures reach the road. From the hills she watches roofs burn in the place she had started to call home.';}},
{id:'child',title:'A question from a child',base:.55,when:s=>s.population>=4,score:s=>pressures.community*.7+s.settlement*.7+s.traits.attachment*.4,resolve:s=>{s.children++;s.bonds++;s.population+=Math.random()<.35?1:0;s.traits.attachment=clamp(s.traits.attachment+.05);s.lore=clamp(s.lore+.045);remember('answered the child about the dead machine');maybeMyth('child',.38);return 'A child born after Mara arrived asks what the dead machine was for. Mara tells the truth: she does not know. Then she tells a story. Years later, people remember only the story.';}},
{id:'machine',title:'The machine remembers',base:.45,score:s=>pressures.technology*.9+pressures.fate*.95+pressures.mystery*.72+s.memory.length*.035,resolve:s=>{s.techAwake=clamp(s.techAwake+.12);s.lore=clamp(s.lore+.09);s.morals.truthBelonging=clamp(s.morals.truthBelonging-.035);s.traits.curiosity=clamp(s.traits.curiosity+.04);remember('heard the machine remember');maybeMyth('machine',.52);const msg=choice(['MARA // RETURN VECTOR','LIFE INDEX: '+s.generation,'MEMORY IS NOT IDENTITY','DO NOT TRUST THE FIRST HISTORY','YOU LEFT THIS MESSAGE']);return `During a windless night the dead machine wakes for eleven seconds. A cracked panel displays: ${msg}. Then every light dies at once.`;}},
{id:'migration',title:'Footsteps on the old road',base:.56,score:s=>pressures.community*.8+pressures.abundance*.65+s.cohesion*.55+(1-pressures.danger)*.3,resolve:s=>{const newcomers=1+Math.floor(Math.random()*4);s.population+=newcomers;s.bonds+=Math.min(2,newcomers);s.settlement=clamp(s.settlement+.05);s.food=clamp(s.food-.03*newcomers);s.cohesion=clamp(s.cohesion+(pressures.community-.5)*.08);return `${newcomers===1?'A traveler arrives':newcomers+' travelers arrive'} on the old road carrying blankets, tools, and contradictory stories of the north. Mara does not invite them to stay. She does not ask them to leave. By winter, there are new doors around the hearth.`;}},
{id:'festival',title:'Lanterns at the hearth',base:.46,when:s=>s.population>=6&&s.cohesion>.5,score:s=>pressures.community*.85+pressures.abundance*.55+s.hope*.5,resolve:s=>{s.cohesion=clamp(s.cohesion+.08);s.hope=clamp(s.hope+.06);s.food=clamp(s.food-.04);s.lore=clamp(s.lore+.035);maybeMyth('festival',.5);return 'Someone hangs small oil lamps from the new roofs. Someone else brings out the three-stringed instrument. Nobody agrees what they are celebrating. By midnight that uncertainty has become part of the tradition.';}},
{id:'invention',title:'A wheel that catches the wind',base:.42,when:s=>s.population>=5,score:s=>pressures.technology*.9+pressures.change*.55+s.traits.ambition*.55+s.techAwake*.6,resolve:s=>{s.techAwake=clamp(s.techAwake+.18);s.food=clamp(s.food+.08);s.settlement=clamp(s.settlement+.06);s.hope=clamp(s.hope+.04);remember('built the wind wheel');maybeMyth('invention',.28);return 'Eren and two others lash scavenged fins to an old axle above the river. After three failures, the wheel turns. A coil salvaged from the dead machine gives off a faint blue glow. For the first time, old technology does something useful.';}},
{id:'schism',title:'The splitting hearth',base:.36,when:s=>s.population>=9,score:s=>(1-s.cohesion)*1.2+pressures.freedom*.5+pressures.danger*.25,resolve:s=>{const leaving=Math.max(2,Math.floor(s.population*(.15+Math.random()*.18)));s.population-=leaving;s.departed+=leaving;s.cohesion=clamp(s.cohesion+.03);s.morals.freedomOrder=clamp(s.morals.freedomOrder+.035);maybeMyth('schism',.44);return `${leaving} people leave before first light, carrying coals from the common fire in a clay bowl. They do not call it exile. Mara does not call it betrayal. A second column of smoke appears beyond the eastern ridge.`;}},
{id:'funeral',title:'A stone for the absent',base:.34,when:s=>s.population>=5,score:s=>pressures.danger*.55+(1-s.health)*.3+s.population*.018,resolve:s=>{s.cohesion=clamp(s.cohesion+.04);s.hope=clamp(s.hope-.025);s.lore=clamp(s.lore+.06);maybeMyth('funeral',.58);return 'The settlement buries one of its own beneath a flat river stone. Nobody can agree on the right words, so each person says one true thing. By evening the grave is surrounded by small objects no one remembers placing there.';}},
{id:'famine',title:'The thin winter',base:.34,when:s=>s.food<.38,score:s=>(1-s.food)*1.3+(1-pressures.abundance)*.9+pressures.danger*.25,resolve:s=>{const loss=Math.min(s.population-1,Math.floor(Math.random()*3));s.population-=loss;s.health=clamp(s.health-.08);s.cohesion=clamp(s.cohesion-.05);s.traits.fear=clamp(s.traits.fear+.035);return `Winter arrives before the stores are ready. Meals become arithmetic. ${loss>0?loss+' people are gone by thaw.':'No one dies, though everyone learns exactly how hunger changes a room.'}`;}},
{id:'quiet',title:'A quiet season',base:.92,score:s=>(1-pressures.danger)*.6+pressures.abundance*.45+(1-pressures.change)*.35,resolve:s=>{s.health=clamp(s.health+.035);s.hope=clamp(s.hope+.03);s.damage=clamp(s.damage-.08*(pressures.community+.4));return choice(['For once, nothing demands heroism. Mara repairs a roof, mends a coat, and learns where the evening light reaches the river.','A season passes without omen or blood. The ordinariness of it feels almost supernatural.','The roads stay quiet. Bread rises. Someone plays the three-stringed instrument badly and often. Mara finds herself hoping it never stops.']);}}
];

function weightedEvent(){const available=events.filter(e=>!e.when||e.when(state));const scored=available.map(e=>({e,w:Math.max(.015,e.base*Math.max(.05,e.score(state))*(.72+pressures.fate*Math.random()*.92))}));const total=scored.reduce((a,x)=>a+x.w,0);let r=Math.random()*total;for(const x of scored){r-=x.w;if(r<=0)return x.e;}return scored.at(-1).e;}
function turnWheel(){if(!state.alive)return;drift();const ev=weightedEvent();state.lastEvent=ev.id;state.chapter=ev.title;const text=ev.resolve(state);logStory(text);addHistory(ev.title,text);advanceSeason();naturalGrowth();updateUI();flashOmen(ev.title);updateWorldTarget();if(state.health<=.06||state.age>80||(pressures.danger>.92&&Math.random()<.05))endLife();}
function drift(){const t=state.traits,m=state.morals;t.fear=clamp(t.fear+(pressures.danger-.5)*.018-(pressures.community-.5)*.008);t.compassion=clamp(t.compassion+(pressures.community-.5)*.012-(pressures.danger-.65)*.006);t.curiosity=clamp(t.curiosity+(pressures.mystery-.5)*.012);t.ambition=clamp(t.ambition+(pressures.change-.5)*.009+(pressures.technology-.5)*.006);t.resolve=clamp(t.resolve+(pressures.danger-.5)*.006);t.attachment=clamp(t.attachment+(pressures.community-.5)*.008);m.freedomOrder=clamp(m.freedomOrder+(pressures.freedom-.5)*.015-(pressures.danger-.5)*.008);m.preserveChange=clamp(m.preserveChange+(pressures.change-.5)*.015);state.cohesion=clamp(state.cohesion+(pressures.community-.5)*.018-(pressures.danger-.6)*.008);state.food=clamp(state.food+(pressures.abundance-.5)*.025-state.population*.0015);state.settlement=clamp(state.settlement+(pressures.community-.45)*.010+(pressures.abundance-.5)*.006);state.water=clamp(state.water+(pressures.abundance-.5)*.008-(pressures.change-.5)*.004);state.damage=clamp(state.damage-(pressures.community*.035+pressures.abundance*.02));}
function naturalGrowth(){if(state.population>1&&state.food>.52&&state.cohesion>.48&&Math.random()<.15+pressures.community*.12)state.population++;if(state.food<.22&&state.population>2&&Math.random()<.32)state.population--;}
function advanceSeason(){state.season++;if(state.season>3){state.season=0;state.year++;state.age++;}}
function logStory(text){document.getElementById('story').textContent=text;}
function endLife(){state.alive=false;state.paused=true;const candidates=[{trait:'compassion',delta:.06,phrase:'the sight of an empty chair produces grief without explanation'},{trait:'fear',delta:-.05,phrase:'thunder feels less frightening than it should'},{trait:'curiosity',delta:.07,phrase:'locked doors feel like invitations'},{trait:'attachment',delta:.07,phrase:'the smell of woodsmoke feels like returning home'},{trait:'resolve',delta:.07,phrase:'the western ridge seems important before she knows why'}];soulEchoes=[choice(candidates)];if(state.memory.length>5&&Math.random()<.55)soulEchoes.push(choice(candidates));if(state.myths.length)legacy.myths.push(choice(state.myths));legacy.myths=[...new Set(legacy.myths)].slice(-12);state.chapter='The last turning';const text=`Mara's life ends in Year ${state.year}. The world continues without asking permission. Some things vanish. Some become stories. Something smaller than memory refuses to disappear.`;logStory(text);addHistory(state.chapter,text);document.getElementById('pauseBtn').textContent='Ended';updateUI();flashOmen('A life becomes an echo');}

const sliderHost=document.getElementById('sliders');Object.keys(pressures).forEach(k=>{const wrap=document.createElement('div');wrap.innerHTML=`<div class="labelrow"><span>${pressureLabels[k]}</span><span class="val" id="v-${k}">${Math.round(pressures[k]*100)}</span></div><input id="s-${k}" type="range" min="0" max="100" value="${pressures[k]*100}">`;sliderHost.appendChild(wrap);wrap.querySelector('input').addEventListener('input',e=>{pressures[k]=+e.target.value/100;document.getElementById('v-'+k).textContent=e.target.value;updateWorldTarget();});});
const moralDefs=[['selfOthers','Self','Others'],['mercyJustice','Justice','Mercy'],['freedomOrder','Order','Freedom'],['truthBelonging','Belonging','Truth'],['preserveChange','Preserve','Change']];
function updateUI(){document.getElementById('dateLine').textContent=`Year ${state.year} · ${seasons[state.season]}`;document.getElementById('chapter').textContent=state.chapter;document.getElementById('age').textContent=`Age ${state.age}`;document.getElementById('generation').textContent=`Life ${roman(state.generation)}`;document.getElementById('place').textContent=state.settlement>.72?'Hearthstead':state.settlement>.42?'The New Hearth':'The Hollow';document.getElementById('population').textContent=state.population<=1?'Alone':`${state.population} souls`;const traits=document.getElementById('traits');traits.innerHTML='';Object.entries(state.traits).forEach(([k,v])=>traits.insertAdjacentHTML('beforeend',`<div class="pill"><b>${k}</b><span>${Math.round(v*100)}</span></div>`));const m=document.getElementById('morals');m.innerHTML='';moralDefs.forEach(([k,l,r])=>m.insertAdjacentHTML('beforeend',`<div class="labelrow"><span>${l}</span><span>${r}</span></div><div class="moralbar"><i style="width:${Math.round(state.morals[k]*100)}%"></i></div>`));const t=state.traits,desc=[];if(t.compassion>.66)desc.push('tender toward strangers');else if(t.compassion<.38)desc.push('guarded with mercy');if(t.fear>.62)desc.push('watchful');if(t.curiosity>.68)desc.push('drawn toward unanswered things');if(t.resolve>.65)desc.push('difficult to move once decided');if(t.attachment>.62)desc.push('deeply rooted in people and place');document.getElementById('soulLine').textContent=`Mara is ${desc.length?desc.join(', '):'still becoming someone the world can name'}.`;document.getElementById('popChip').textContent=state.population;document.getElementById('cohesionChip').textContent=Math.round(state.cohesion*100);document.getElementById('foodChip').textContent=Math.round(state.food*100);document.getElementById('loreChip').textContent=Math.round(state.lore*100);document.getElementById('echoChip').textContent=legacy.echoStones;const hist=document.getElementById('history');hist.innerHTML='';state.history.slice(0,4).forEach((h,i)=>hist.insertAdjacentHTML('beforeend',`<div class="history-item ${i===0?'active':''}" title="${h.text.replaceAll('"','&quot;')}">Y${h.year} · ${h.title}</div>`));const myths=[...state.myths,...legacy.myths].filter((x,i,a)=>a.indexOf(x)===i);document.getElementById('legacyLine').textContent=myths.length?`People currently repeat: “${myths.slice(-3).join('” · “')}”`:'No myths have survived long enough to become traditions.';}
function roman(n){return ['I','II','III','IV','V','VI','VII','VIII','IX','X'][n-1]||String(n)}
function flashOmen(t){const o=document.getElementById('omen');o.textContent=t;o.style.opacity=1;setTimeout(()=>o.style.opacity=0,1600)}

document.getElementById('pauseBtn').onclick=()=>{if(!state.alive)return;state.paused=!state.paused;document.getElementById('pauseBtn').textContent=state.paused?'Resume':'Pause';};let speedIndex=0;const speeds=[1,2,4];document.getElementById('speedBtn').onclick=()=>{speedIndex=(speedIndex+1)%speeds.length;state.speed=speeds[speedIndex];document.getElementById('speedBtn').textContent=state.speed+'× Time';};document.getElementById('nudgeBtn').onclick=turnWheel;document.getElementById('rebirthBtn').onclick=()=>{if(state?.alive){soulEchoes=[{trait:'attachment',delta:state.traits.attachment>.55?.05:-.02,phrase:'the sight of the river feels painfully intimate'},{trait:'resolve',delta:state.traits.resolve>.6?.05:0,phrase:'an old scar aches on skin that has never been wounded'}];}newLife(true);document.getElementById('pauseBtn').textContent='Pause';updateWorldTarget();};
